### ISSUE TITLE
Missing property Quantity on Parcel

### ISSUE THREAD

**Issue by pvdberge** [janssenr/SendCloudApi.Net#10]
Please add Quantity property on Parcel to support multi-collo shipments.

**Comment by janssenr** [comment]
Added Quantity property on CreateParcel to support multi-collo shipments
See:
https://github.com/janssenr/SendCloudApi.Net/commit/0c38d9c1ca1088f2c81e329976b39a79baf375ce

**Comment by pvdberge** [comment]
That's quick, thanks!
