### ISSUE TITLE
Client.ShippingMethods.Get() does not support return labels

### ISSUE THREAD

**Issue by RubinhoD** [janssenr/SendCloudApi.Net#11]
Hi,

The Client.ShippingMethods.Get() gives us all possible shippingmethods for normal parcels.
If you want to get the shipping methods for return parcels, according to the SendCloud docs, you must add the parameter is_return (true).

This parameter is not provided in the api. Is there a way to obtain these shipping methods or can you add the parameter?

**Comment by janssenr** [comment]
I added the isReturn parameter
