### ISSUE TITLE
Error deserializing

### ISSUE THREAD

**Issue by veronicaDesantis** [janssenr/SendCloudApi.Net#12]
Hi,
following your instruction in creating a parcel this is the error we are getting:

The data contract type 'SendCloudApi.Net.Models.Country' cannot be deserialized because the required data members 'from_id, from_iso_2, from_iso_3, from_name' were not found.'

This is the code:
`var parcel = new CreateParcel
            {
                Name = "John Smith",
                CompanyName = "ACME",
                Address = "Wellingtonstreet 25",
                City = "Wellington",
                PostalCode = "3423 DD",
                Country = "NL",
                RequestLabel = true,
                ShippingMethod = 8, // Shipping method, get possibilities from client.ShippingMethods.Get()
                OrderNumber = "ORDER2014-52321",
            };
            try
            {
                var response = await client.Parcels.Create(parcel);
            }
            catch (SendCloudException e)
            {
                throw new Exception(e.Message);
            }`

**Comment by janssenr** [comment]
Should be fixed now.
Set IsRequired to false for Country fields

**Comment by veronicaDesantis** [comment]
Thank you!
