### ISSUE TITLE
Issue when errors encounted

### ISSUE THREAD

**Issue by davidkdb** [janssenr/SendCloudApi.Net#13]
Hi,

We had a big struggle to debug a problem with a shipment.

Using the GetShipments.

The value of shipping_method was null, but the error was triggered on the json parsing with a invalid value on int32 (but not which).

I downloaded the code, and found out by setting the shipping_method to int? it would not fail here, and by adding the errors properties these errors can actually be read.

This would be much more useful to show the user also. And another benefit would be that a shipment can actually be validated in the GetShipments with a list of validation errors.

I only made a change in the Shipment.cs

Should I upload it to here, or send it to you?

We would really like to use the "official" package, rather than fixing this locally ourselves.

**Comment by janssenr** [comment]
Hi,

You can upload it to here or send it to me.

**Comment by davidkdb** [comment]
Hi Rob,

Just sent you an email.

**Comment by janssenr** [comment]
Make ShippingMethodId nullable and Added Errors property to Shipment.cs
