### ISSUE TITLE
Creating Multicollo Parcels

### ISSUE THREAD

**Issue by JavPer73** [janssenr/SendCloudApi.Net#26]
I am struggling to create multicollo parcels (RequestLabel = true)

If I use Parcels.Create(parcel) with quantity >1 I get an exception 'Requesting a label for a multi-collo shipment in only allowed via creating multiple parcels"

So I tried with Parcels.BulkCreate(new CreateParcel[] { parcel }) with the same parcel object as before but I got independent labels who are not detected as Multicollo.  

Is there a specific method I haven't found?

**Comment by JavPer73** [comment]
Just checked and there are tons of variables here, for example if the carrier supports multi-collo. Just want to be sure I am using the right methods of his API.

Thanks!

**Comment by janssenr** [comment]
https://sendcloud.dev/docs/shipping/multicollo/?_gl=1*1ismcq4*_ga*MjAyNTEwODY0OS4xNzAxMTczMzMx*_ga_G20N49N1GG*MTcwMTE3MzMzMC4xLjEuMTcwMTE3MzgwNS40OC4wLjA.

How to create multicollo shipments
To create a multicollo, include the number of parcels you wish to ship in the quantity field under the parcel object, and make a 
`POST` request to the [Create multiple parcels endpoint](https://api.sendcloud.dev/docs/sendcloud-public-api/parcels/operations/create-a-parcel?_gl=1*1p4wvzv*_ga*MjAyNTEwODY0OS4xNzAxMTczMzMx*_ga_G20N49N1GG*MTcwMTE3MzMzMC4xLjEuMTcwMTE3Mzg4Ni42MC4wLjA.). The maximum number of parcels you can create under quantity is 20.

- If the value of request_label is true, then the parcels will be announced together, and the response will include the URL to download each individual shipping label.
- If the value of request_label is false, the parcel object will be created with a quantity matching the value you specified in your request. The parcel will appear in the Incoming order overview of the Sendcloud panel with the status “Ready to process”. When the parcel is processed, the correct number of shipping labels will be created.

**Comment by janssenr** [comment]
But the array can also contain just 1 parcel.
It's about the Quantity property.
The example below creates 3 parcels for DPD, because the Quantity is set to 3.

When you print the labels there will be a section with "Packages 1 of 3", "Packages 2 of 3", "Packages 3 of 3"
![image](https://github.com/janssenr/SendCloudApi.Net/assets/7270617/0570a11b-0f8f-49ab-a762-02cc7f5060bc)

```
            var parcels = new[]
            {
                new CreateParcel
                {
                    Name = "John Doe",
                    CompanyName = "SendCloud",
                    Address = "Insulindelaan",
                    HouseNumber = "115",
                    City = "Eindhoven",
                    PostalCode = "5642CV",
                    Telephone = "+31612345678",
                    Email = "john@doe.nl",
                    Country = "NL",
                    Shipment = new ShippingMethod { Id = 4203 },
                    Weight = 10.000,
                    OrderNumber = "1",
                    InsuredValue = 0,
                    TotalOrderValue = "11.11",
                    TotalOrderValueCurrency = "EUR",
                    Quantity = 3,
                    RequestLabel = true,
                }
            };
            var response = await _apiV2.Parcels.BulkCreate(parcels);

```

Is this what you mean?

**Comment by JavPer73** [comment]
As I wrote in the opening message

_So I tried with Parcels.BulkCreate(new CreateParcel[] { parcel }) with the same parcel object as before but I got independent labels who are not detected as Multicollo._

But it was with MRW, if we check

 https://support.sendcloud.com/hc/en-us/articles/360038716852-How-to-create-multicollo-shipments-#2

it has a lot of requirements:

MRW

    Only available if you have a direct contract
    Set label preferences directly in MRW (have parcels displayed as 1, 2, 3  or as 1/3, 2/3, 3/3, etc.) 
    Parcel dimensions are mandatory. To automate this, use our [Boxes feature](https://support.sendcloud.com/hc/en-us/articles/360059184551).

I just wanted to be sure I was using the right API calls before continuing to do more tests with other carriers.
