### ISSUE TITLE
Client.ShippingProducts.Get() is missing the returns parameter

### ISSUE THREAD

**Issue by RubinhoD** [janssenr/SendCloudApi.Net#27]
Hi,

I'm using the ShippingProducts Api to receive the available shipping methods between 2 countries.

Client.ShippingProducts.Get("[FROMCOUNTRY]", "[TOCOUNTRY]")
SendCloud also supports the "Returns" (boolean) parameter to receive only shipping methods for return labels from any country to our warehouse.

Is it possible to provide this parameter in your library?

Many thanks

**Comment by janssenr** [comment]
Hi,

It's already possible by using the functionalities param.
Example:
```
            string fromCountry = "FR";
            string toCountry = "NL";
            Dictionary<string, string> functionalities = new Dictionary<string, string>
            {
                { "returns" , "true" }
            };
            var results = await Client.ShippingProducts.Get(fromCountry, toCountry, functionalities);

```

**Comment by RubinhoD** [comment]
Great thanks, i'll try
