### ISSUE TITLE
Create parcel, add contractId is not possible

### ISSUE THREAD

**Issue by RubinhoD** [janssenr/SendCloudApi.Net#29]
When we have multiple contracts of the same carrier, we need to add the Id of the contract in the CreateParcel Request.
At this moment it's not a property in the CreateParcel object.

https://api.sendcloud.dev/docs/sendcloud-public-api/parcels/operations/create-a-parcel

Could this be added ?

Thanks

**Comment by janssenr** [comment]
I added contract as a property
