### ISSUE TITLE
DateTime problems and missing fields

### ISSUE THREAD

**Issue by davidkdb** [janssenr/SendCloudApi.Net#8]
You should use DateTimeOffset instead of DateTime on all date fields returned.

These fields are actually DateTimeOffset fields from Sendcloud, but for some reason are treated as DateTime.

I made a test myself with RestAPI and with for example shipment I set the created_at to DateTimeOffset and it returned {08.03.2021 11:24:25 +01:00}. Your API returned {08.03.2021 10:24:25} that will be incorrect if the time zone is different from UTC. In general DateTimeOffset is better since we dont need to worry about time zone issues.

Also fields are missing. For example in Shipment the allowed_shipping_methods field is missing, and we need this.

**Comment by janssenr** [comment]
Added allowed_shipping_methods and some other Shipment properties
So the missing fields should be solved.

Can you share your DateTimeOffset example with me? Because I get an error when using DateTimeOffset

**Comment by davidkdb** [comment]
I have sent you an email with our test program

**Comment by davidkdb** [comment]
Any news ?

**Comment by davidkdb** [comment]
Still waiting for a feedback

**Comment by janssenr** [comment]
I added the missing fields.
Still looking into DateTimeOffset.
But SendCloud returns the Date in UTC.
So you can use parcel.DateCreated.ToLocalTime() to get the correct DateTime
