### ISSUE TITLE
Error message when creating parcel

### ISSUE THREAD

**Issue by davidkdb** [janssenr/SendCloudApi.Net#9]
![pic1](https://user-images.githubusercontent.com/57062216/116089163-dac21f80-a6a2-11eb-9a60-c0c55ee555c0.jpg)

Also when getting a list of shipments and some of them has errors, like missing address, weight etc serialization fails.

**Comment by janssenr** [comment]
Do you have example code with which I can reproduce the error?

**Comment by janssenr** [comment]
According to the SendCloud API documentation ParcelItem.Value is a required field:
https://docs.sendcloud.sc/api/v2/shipping/#create-a-parcel
So when sending a ParcelItem so have to fill the Value field.
